language: php

sudo: false

php:
  - 7.1
  - 7.2
  - 7.3

matrix:
  fast_finish: true
  include:
    - php: 7.1
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: 7.3
      env: SYMFONY_VERSION=3.1.* COVERAGE=true

cache:
  directories:
    - $HOME/.composer/cache/files

before_script:
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;
  - composer update --prefer-dist --no-interaction $COMPOSER_FLAGS

phpunit: if [ "$COVERAGE" == true ]; then phpunit --coverage-text; else phpunit; fi
